#!/bin/bash


CHECKPOINT_PATH="/home/ubuntu/code/A"

# Vocabulary file generated by the preprocessing script.
SKIP_THOUGHTS_VOCAB="./skip_thoughts/data/vocab.txt"

# Path to downloaded word2vec model.
WORD2VEC_MODEL="/home/ubuntu/GoogleNews-vectors-negative300.bin"

# Output directory.
EXP_VOCAB_DIR="/home/ubuntu/code/A_skip_thoughts_2/expanded"

# Build the vocabulary expansion script.
bazel build -c opt skip_thoughts/vocabulary_expansion

# Run the vocabulary expansion script.
bazel-bin/skip_thoughts/vocabulary_expansion \
  --skip_thoughts_model=${CHECKPOINT_PATH} \
  --skip_thoughts_vocab=${SKIP_THOUGHTS_VOCAB} \
  --word2vec_model=${WORD2VEC_MODEL} \
  --output_dir=${EXP_VOCAB_DIR}
